### ISSUE TITLE
order number format issue

### ISSUE THREAD

**Issue by varghesejose2020** [ubucon-asia/2021#38]
My Eventyay ticket Order Number format: O1234567890-12345/12345 (O{10 digits}-{5digits}/{5digits})
but in the [ubucon venue](https://2021.ubucon.asia/venue/) the order number format is different @sukso96100

**Comment by sukso96100** [comment]
Hi, seems like you downloaded ticket not invoice. 
If that number is the only on you were able to find, simply give booth staffs the your code without last `/{5 digits}`
